spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "http://localhost:5174"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
      routes:
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/user-management-service/api/users/**
          filters:
            - RemoveResponseHeader=Access-Control-Allow-Origin

        - id: course-management-service
          uri: lb://course-management-service
          predicates:
            - Path=/course-management-service/api/courses/**

        - id: enrollment-service
          uri: lb://enrollmentservice
          predicates:
            - Path=/enrollment-service/api/enrollments/**

        - id: content-delivery-service
          uri: lb://content-delivery-service
          predicates:
            - Path=/content-delivery-service/api/content/**

eureka:
  client:
    service-url:
      defaultZone: http://course-platform-eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8765

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,loggers,beans
  endpoint:
    health:
      show-details: always

