spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://localhost:4173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/user-management-service/api/users/**

        - id: course-management-service
          uri: lb://course-management-service
          predicates:
            - Path=/course-management-service/api/courses/**

        - id: course-management-service-reviews
          uri: lb://course-management-service
          predicates:
            - Path=/course-management-service/api/reviews/**

        - id: enrollment-service
          uri: lb://enrollmentservice
          predicates:


        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/api/payments/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/api/notifications/**

        - id: content-delivery-service-content
          uri: lb://content-delivery-service
          predicates:
            - Path=/content-delivery-service/api/content/**

        - id: content-delivery-service-logs
          uri: lb://content-delivery-service
          predicates:
            - Path=/content-delivery-service/api/logs/**

eureka:
  client:
    service-url:
      defaultZone: http://course-platform-eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8765

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,gateway
  endpoint:
    health:
      show-details: always
