server:
  port: 8085

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://course-platform-mysql:3306/notification_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,loggers,beans
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://course-platform-eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework: INFO
    com.courseselling: DEBUG
