pipeline {
    agent any
    environment {
        IMAGE = "rugved2211/config-server"
        TAG = "${env.BUILD_NUMBER}"
    }
    stages {
        stage('Checkout') { steps { checkout scm } }
        stage('Build')   { steps { sh 'mvn clean package -DskipTests=true' } }
        stage('Test')    { steps { sh 'mvn test' }
            post { always { junit '**/target/surefire-reports/*.xml' } } }
        stage('Docker Build & Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        def img = docker.build("${IMAGE}:${TAG}")
                        img.push()
                    }
                }
            }
        }
    }
}
