pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "rugved2211/user-management-service:latest"
        REGISTRY_CREDENTIALS = 'dockerhub-creds' // Jenkins credential ID for DockerHub
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir('user-management-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage('Test') {
            steps {
                dir('user-management-service') {
                    sh 'mvn test'
                }
            }
        }
        stage('Docker Build') {
            steps {
                dir('user-management-service') {
                    script {
                        docker.build(DOCKER_IMAGE, '.')
                    }
                }
            }
        }
        stage('Docker Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', REGISTRY_CREDENTIALS) {
                        docker.image(DOCKER_IMAGE).push()
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Add deployment steps here (kubectl or docker-compose)'
            }
        }
    }
}
